# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='session',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
